import React from 'react';
import {
  useCurrentFrame,
  useVideoConfig,
  interpolate,
  Audio,
  Video,
  Img,
  staticFile,
  AbsoluteFill,
  Series,
  Easing,
} from 'remotion';

// Import local JSON structure generated by Python script
import estructura from '../public/cocodrilo_estructura.json';

interface Escena {
  id: number;
  bloque: string;
  durationInSeconds: number;
  durationInFrames: number;
  audioTexto: string;
  subtitulo: string;
  geminiPrompt: string;
  clipVideo: string;
  keyframeFallback: string;
}

const SubtituloCocodrilo: React.FC<{ subtitulo: string; bloque: string }> = ({
  subtitulo,
  bloque,
}) => {
  const frame = useCurrentFrame();

  const opacity = interpolate(frame, [0, 15, 280, 295], [0, 1, 1, 0], {
    extrapolateRight: 'clamp',
  });

  const scale = interpolate(frame, [0, 15], [0.95, 1], {
    easing: Easing.out(Easing.back(1.5)),
    extrapolateRight: 'clamp',
  });

  return (
    <>
      {/* Badge Top Left: Pensamientos del personaje */}
      <div
        style={{
          position: 'absolute',
          top: 40,
          left: 40,
          backgroundColor: 'rgba(0, 0, 0, 0.65)',
          color: '#4ADE80', // green-400
          padding: '10px 20px',
          borderRadius: 8,
          border: '1px solid rgba(74, 222, 128, 0.4)',
          fontFamily: "'Inter', sans-serif",
          fontSize: 18,
          fontWeight: 600,
          letterSpacing: 1,
          backdropFilter: 'blur(8px)',
          boxShadow: '0 4px 12px rgba(0,0,0,0.5)',
        }}
      >
        🐊 {bloque}
      </div>

      {/* Box Bottom Center: Subtítulos dinámicos estilizados */}
      <div
        style={{
          position: 'absolute',
          bottom: 70,
          left: 60,
          right: 60,
          display: 'flex',
          justifyContent: 'center',
          opacity,
          transform: `scale(${scale})`,
        }}
      >
        <div
          style={{
            backgroundColor: 'rgba(10, 15, 10, 0.85)',
            color: '#FFFFFF',
            fontFamily: "'Inter', sans-serif",
            fontWeight: 700,
            fontSize: 32,
            textAlign: 'center',
            padding: '20px 36px',
            borderRadius: 16,
            maxWidth: 1200,
            border: '2px solid #22C55E', // green-500
            boxShadow: '0 10px 30px rgba(0,0,0,0.8), 0 0 20px rgba(34, 197, 94, 0.25)',
            lineHeight: 1.35,
          }}
        >
          {subtitulo}
        </div>
      </div>
    </>
  );
};

export const VideoCocodriloFilosofo: React.FC = () => {
  const { fps } = useVideoConfig();

  return (
    <AbsoluteFill style={{ backgroundColor: '#050B05' }}>
      {/* Master Ambient Audio Track */}
      <Audio src={staticFile('Satin_Maceo_AIR_Flow_Master.wav')} loop volume={0.3} />

      {/* Series Loop para las 120 escenas (20 minutos) */}
      <Series>
        {estructura.scenes.map((escena: Escena) => {
          return (
            <Series.Sequence
              key={escena.id}
              durationInFrames={escena.durationInFrames}
            >
              <AbsoluteFill style={{ backgroundColor: '#050B05' }}>
                {/* Visual Layer: Muestra el Fallback Keyframe o Clip MP4 */}
                <Img
                  src={staticFile(escena.keyframeFallback)}
                  style={{
                    width: '100%',
                    height: '100%',
                    objectFit: 'cover',
                  }}
                />

                {/* Layer de Subtítulos y UI */}
                <SubtituloCocodrilo
                  subtitulo={escena.subtitulo}
                  bloque={escena.bloque}
                />
              </AbsoluteFill>
            </Series.Sequence>
          );
        })}
      </Series>
    </AbsoluteFill>
  );
};
